build:
    environment:
        php: 5.4
        elasticsearch: 1.4.3

    tests:
        override:
            -
                command: vendor/bin/phpunit -c phpunit.xml --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover
filter:
    excluded_paths:
        - "tests/*"


build_failure_conditions:
    # new classes/methods with a rating of C or worse
    - 'elements.rating(<= C).new.exists'

    # new major or worse issue
    - 'issues.severity(>= MAJOR).new.exists'

    # code quality rating drops below a specific value
    - 'project.metric("scrutinizer.quality", < 9.0)'
